#springcloud
eureka:
  client:
    serviceUrl:
    #eureka注册中心地址
      defaultZone: http://localhost:8888/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/hwg?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  #jpa
  jpa:
    #mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #jpa有表更新 无表创建
    hibernate:
      ddl-auto: update
  application:
    #注册中心 服务名称
    name: huangjiong
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
server:
  port: 8010
#logback
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    #扫描路径  及输出级别
    com.hwg.repository: debug
          