eureka:
  client:
    serviceUrl:
    #eureka注册中心地址
      defaultZone: http://localhost:8888/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gezhenzhen?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
  #服务名称,随便写
    name: gezhenzhen 
server:
  port: 8020
          