eureka:
  client:
    serviceUrl:
    #eureka注册中心地址
      defaultZone: http://localhost:8888/eureka/
server:
#项目端口号
  port: 8030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhulonghaodb?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate: 
      ddl-auto: update
  application:
  #服务名称,随便写
    name: zhulonghao

### 数据源配置6666
#spring.datasource.url=jdbc:mysql://localhost:3306/springbootall?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
##JPA配置
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
##运行时输出jpa执行的sql语句
#spring.jpa.show-sql=true
## spring-boot-starter-data-jpa自动映射创建表动作 配置: 有表更新,无表创建
#spring.jpa.hibernate.ddl-auto=update