eureka:
  client:
    serviceUrl:
    #eureka注册中心地址eureka.client.healthcheck.enabled=true
      defaultZone: http://localhost:8888/eureka/
   
server:
#项目端口号
  port: 8007
#tomcat最大并发线程数
  tomcat:
    max-threads: 30
spring:
  application:
  #服务名称,随便写
    name: service-oauth2
#启用Feign中hystrix熔断器、依赖隔离、服务降级
feign:
   hystrix:
     enabled: true
#熔断器启用
#feign.hystrix.enabled=true
#hystrix.command.default.execution.timeout.enabled=true
#断路器的超时时间,下级服务返回超出熔断器时间，即便成功，消费端消息也是TIMEOUT,所以一般断路器的超时时间需要大于ribbon的超时时间。
#服务的返回时间大于ribbon的超时时间，会触发重试
##默认=1000,太小,修改为50秒
hystrix:
   command: 
     default: 
       execution:
         timeout:
           enabled: true
         isolation:
           thread: 
             timeoutInMilliseconds: 50000
 