eureka:
  client:
    serviceUrl:
    #eureka注册中心地址
      defaultZone: http://localhost:8888/eureka/
        #eureka注册中心展示的微服务信息页面,默认为 http://localhost:${server.port}/info
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
server:
#项目端口号
  port: 8040
spring:
  application:
  #服务名称,随便写
    name: liuwenjin
  ## 数据源配置 
  datasource:
    url: jdbc:mysql://localhost:3306/liuwenjin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  ##JPA配置 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate: 
      ddl-auto: update
  ##rabbitmq配置 
  ##rabbitmq:
    ##host: localhost
    ##port: 5672
    ##username: guest
    ##password: guest
